/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Backend.AppManager;
import Backend.Message;
import Backend.MessageManager;

import Backend.StudentManager;
import Backend.DB;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Narita
 */
public class AdminMainUI extends javax.swing.JFrame {

    private StudentManager sm;
    private MessageManager mm;

    /**
     * Creates new form AdminMainUI
     */
    public AdminMainUI() {

        initComponents();
        setLocationRelativeTo(null);

//        try {
//            AppManager.init();//remeber only main
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(AdminMainUI.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (SQLException ex) {
//            Logger.getLogger(AdminMainUI.class.getName()).log(Level.SEVERE, null, ex);
//        }

        DefaultListModel<String> listModel = new DefaultListModel<>();
        //populate jlist with admin messages
        try {
            listModel.addAll(AppManager.messageManager.getAdminMessages());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, " SQL error");
            Logger.getLogger(AdminMainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        sentJlist.setModel(listModel);

        DefaultListModel<String> listModel1 = new DefaultListModel<>();
        //populate jlist with student messages
        try {
            listModel1.addAll(AppManager.messageManager.getStudentMessages());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "SQL error");
            Logger.getLogger(AdminMainUI.class.getName()).log(Level.SEVERE, null, ex);

        }
        receivedJlist.setModel(listModel1);

        //topic combo box on stats screen, sort messages by topics
        String[] topics = {"Academics", "Facilities", "Teachers", "Red deli", "Students"};
        DefaultComboBoxModel<String> comboModel = new DefaultComboBoxModel<String>(topics);
        topicCombo.setModel(comboModel);

        //populate combo box with student usernames
        sm = new StudentManager();
        DefaultComboBoxModel<String> studentList = new DefaultComboBoxModel<>();
        try {
            studentList.addAll(AppManager.studentManager.getStudentsUsernameList());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, " SQL error");
            Logger.getLogger(AdminMainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        studentComboBox.setModel(studentList);

        String numOfMessages;
        
        try {
            numOfMessages = AppManager.messageManager.getTotalNumMessages();
            totalMessagesOutput.setText(numOfMessages);
        } catch (SQLException ex) {
            System.out.println("num error ");
            Logger.getLogger(AdminMainUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            //populate testfield with total num of messages
            totalMessagesOutput.setText(AppManager.messageManager.getTotalNumMessages());
            // populate textfields with num of messages according to topic
            academicText.setText(AppManager.messageManager.getNumAcademic());
            facilitiesText.setText(AppManager.messageManager.getNumFacilities());
            teachersText.setText(AppManager.messageManager.getNumTeachers());
            reddeliText.setText(AppManager.messageManager.getNumReddeli());
            studentsText.setText(AppManager.messageManager.getNumStudents());
        } catch (SQLException ex) {
            Logger.getLogger(AdminMainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        // populates combo box with student usernames
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

        try {
            model.addAll(AppManager.studentManager.getStudentsUsernameList());
        } catch (SQLException ex) {
            System.out.println("errorrrrrr");
            Logger.getLogger(AdminMainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        studentsCombo.setModel(model);

    }//end of constructor

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        totalMessagesOutput = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        academicText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        facilitiesText = new javax.swing.JTextField();
        teachersText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        reddeliText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        studentsText = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        adminTextArea = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        messageInput = new javax.swing.JTextArea();
        sendButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        studentComboBox = new javax.swing.JComboBox<>();
        labelll = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        sentJlist = new javax.swing.JList<>();
        viewButton = new javax.swing.JButton();
        refreshLabel = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        sentTextArea = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        receivedJlist = new javax.swing.JList<>();
        viewReceivedButton = new javax.swing.JButton();
        refreshRecLabel = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        receivedTextArea = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        topicCombo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        statsJlist = new javax.swing.JList<>();
        statsViewButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        studentInfoTextArea = new javax.swing.JTextArea();
        searchStudentButton = new javax.swing.JButton();
        studentsCombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(220, 220, 220));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setName(""); // NOI18N
        jTabbedPane1.setOpaque(true);

        jPanel4.setBackground(new java.awt.Color(212, 186, 176));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Total Messages:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        textArea.setBackground(new java.awt.Color(255, 255, 255));
        textArea.setColumns(20);
        textArea.setForeground(new java.awt.Color(0, 0, 0));
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 32405, 320, 132));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Notes:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 32383, -1, -1));

        totalMessagesOutput.setEditable(false);
        totalMessagesOutput.setBackground(new java.awt.Color(255, 255, 255));
        totalMessagesOutput.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(totalMessagesOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Facilities:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Academic:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        academicText.setEditable(false);
        academicText.setBackground(new java.awt.Color(255, 255, 255));
        academicText.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(academicText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Teachers:");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 56, -1));

        facilitiesText.setEditable(false);
        facilitiesText.setBackground(new java.awt.Color(255, 255, 255));
        facilitiesText.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(facilitiesText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        teachersText.setEditable(false);
        teachersText.setBackground(new java.awt.Color(255, 255, 255));
        teachersText.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(teachersText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Red Deli:");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 57, -1));

        reddeliText.setEditable(false);
        reddeliText.setBackground(new java.awt.Color(255, 255, 255));
        reddeliText.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(reddeliText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Students:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        studentsText.setEditable(false);
        studentsText.setBackground(new java.awt.Color(255, 255, 255));
        studentsText.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(studentsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        jLabel14.setFont(new java.awt.Font("Constantia", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(68, 68, 68));
        jLabel14.setText("ADMINISTRATOR DASHBOARD");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 60));

        jLabel18.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Number of messages according to topics:");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jScrollPane7.setForeground(new java.awt.Color(0, 0, 0));

        adminTextArea.setEditable(false);
        adminTextArea.setBackground(new java.awt.Color(255, 255, 255));
        adminTextArea.setColumns(20);
        adminTextArea.setForeground(new java.awt.Color(0, 0, 0));
        adminTextArea.setRows(5);
        adminTextArea.setText(" Some quotes that will hopefully motivate and inspire you:\n---------------------------------------------------------------\n“To infinity and beyond!” -Toy Story, 1995\n\"We can't help everyone, but everyone can help someone\" -\n\"Do your little bit of good where you are; it's those little bits\nof good put together that overwhelm the worl\" - Desmond\nTutu\n\"No matter what people tell you, words and ideas can \nchange the world.\" - Robin Williams\n\"You improve on everything; you're never perfect\" - Max\nVerstappen\n\n\n");
        jScrollPane7.setViewportView(adminTextArea);

        jPanel4.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 360, 270));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 433, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Dashboard", jPanel2);

        jTabbedPane2.setBackground(new java.awt.Color(220, 220, 220));
        jTabbedPane2.setForeground(new java.awt.Color(0, 0, 0));
        jTabbedPane2.setOpaque(true);

        jPanel7.setBackground(new java.awt.Color(193, 171, 173));

        messageInput.setBackground(new java.awt.Color(255, 255, 255));
        messageInput.setColumns(20);
        messageInput.setForeground(new java.awt.Color(0, 0, 0));
        messageInput.setRows(5);
        jScrollPane2.setViewportView(messageInput);

        sendButton.setBackground(new java.awt.Color(187, 187, 187));
        sendButton.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        sendButton.setForeground(new java.awt.Color(0, 0, 0));
        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        clearButton.setBackground(new java.awt.Color(187, 187, 187));
        clearButton.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        clearButton.setForeground(new java.awt.Color(0, 0, 0));
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("To:");

        studentComboBox.setBackground(new java.awt.Color(255, 255, 255));
        studentComboBox.setForeground(new java.awt.Color(0, 0, 0));

        labelll.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        labelll.setForeground(new java.awt.Color(0, 0, 0));
        labelll.setText("i");
        labelll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelllMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(clearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sendButton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(studentComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelll)
                .addGap(18, 18, 18))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelll)
                .addGap(2, 2, 2)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sendButton)
                    .addComponent(clearButton))
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Reply", jPanel7);

        jPanel8.setBackground(new java.awt.Color(193, 171, 173));

        sentJlist.setBackground(new java.awt.Color(255, 255, 255));
        sentJlist.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        sentJlist.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(sentJlist);

        viewButton.setBackground(new java.awt.Color(187, 187, 187));
        viewButton.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        viewButton.setForeground(new java.awt.Color(0, 0, 0));
        viewButton.setText("VIEW");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        refreshLabel.setForeground(new java.awt.Color(0, 0, 0));
        refreshLabel.setText("Refresh");
        refreshLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshLabelMouseClicked(evt);
            }
        });

        sentTextArea.setBackground(new java.awt.Color(255, 255, 255));
        sentTextArea.setColumns(20);
        sentTextArea.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        sentTextArea.setForeground(new java.awt.Color(0, 0, 0));
        sentTextArea.setRows(5);
        jScrollPane8.setViewportView(sentTextArea);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(refreshLabel)
                        .addGap(289, 289, 289))
                    .addComponent(viewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(20, 20, 20))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(refreshLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewButton)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Sent", jPanel8);

        jPanel9.setBackground(new java.awt.Color(193, 171, 173));

        receivedJlist.setBackground(new java.awt.Color(255, 255, 255));
        receivedJlist.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        receivedJlist.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane4.setViewportView(receivedJlist);

        viewReceivedButton.setBackground(new java.awt.Color(187, 187, 187));
        viewReceivedButton.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        viewReceivedButton.setForeground(new java.awt.Color(0, 0, 0));
        viewReceivedButton.setText("VIEW");
        viewReceivedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewReceivedButtonActionPerformed(evt);
            }
        });

        refreshRecLabel.setForeground(new java.awt.Color(0, 0, 0));
        refreshRecLabel.setText("Refresh");
        refreshRecLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshRecLabelMouseClicked(evt);
            }
        });

        receivedTextArea.setBackground(new java.awt.Color(255, 255, 255));
        receivedTextArea.setColumns(20);
        receivedTextArea.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        receivedTextArea.setForeground(new java.awt.Color(0, 0, 0));
        receivedTextArea.setRows(5);
        jScrollPane9.setViewportView(receivedTextArea);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewReceivedButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(refreshRecLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(16, 16, 16))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(refreshRecLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewReceivedButton)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Received", jPanel9);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 427, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Messages", jPanel3);

        jPanel5.setBackground(new java.awt.Color(127, 134, 123));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Concern catagory:");

        topicCombo.setBackground(new java.awt.Color(187, 187, 187));
        topicCombo.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        topicCombo.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Sort by topic:");

        statsJlist.setBackground(new java.awt.Color(255, 255, 255));
        statsJlist.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        statsJlist.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane6.setViewportView(statsJlist);

        statsViewButton.setBackground(new java.awt.Color(187, 187, 187));
        statsViewButton.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        statsViewButton.setForeground(new java.awt.Color(0, 0, 0));
        statsViewButton.setText("VIEW");
        statsViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statsViewButtonActionPerformed(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(187, 187, 187));
        searchButton.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        searchButton.setForeground(new java.awt.Color(0, 0, 0));
        searchButton.setText("search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(statsViewButton)
                .addGap(143, 143, 143))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(topicCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchButton)
                                .addGap(8, 8, 8)))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(topicCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchButton)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(statsViewButton)
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Sort by Topic", jPanel5);

        jPanel10.setBackground(new java.awt.Color(199, 199, 187));

        studentInfoTextArea.setEditable(false);
        studentInfoTextArea.setBackground(new java.awt.Color(255, 255, 255));
        studentInfoTextArea.setColumns(20);
        studentInfoTextArea.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        studentInfoTextArea.setForeground(new java.awt.Color(0, 0, 0));
        studentInfoTextArea.setRows(5);
        jScrollPane5.setViewportView(studentInfoTextArea);

        searchStudentButton.setBackground(new java.awt.Color(187, 187, 187));
        searchStudentButton.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        searchStudentButton.setForeground(new java.awt.Color(0, 0, 0));
        searchStudentButton.setText("Search");
        searchStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchStudentButtonActionPerformed(evt);
            }
        });

        studentsCombo.setBackground(new java.awt.Color(255, 255, 255));
        studentsCombo.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        studentsCombo.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Search for a specific student's information");

        jLabel15.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("i");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addGap(66, 66, 66))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(studentsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchStudentButton)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchStudentButton)
                    .addComponent(studentsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Search Student", jPanel10);

        jPanel11.setBackground(new java.awt.Color(239, 237, 231));
        jPanel11.setForeground(new java.awt.Color(0, 0, 0));
        jPanel11.setPreferredSize(new java.awt.Dimension(500, 432));

        jLabel13.setFont(new java.awt.Font("Courier New", 3, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Help those in need");

        exitButton.setBackground(new java.awt.Color(187, 187, 187));
        exitButton.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        exitButton.setForeground(new java.awt.Color(0, 0, 0));
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("You will never regret being good");

        jLabel17.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("to others during their time of need");

        jLabel7.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("NEVER BACK DOWN NEVER WHAT?");

        jLabel19.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("NEVER GIVE UP!");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(jLabel13))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel16))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel17))))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel19))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(exitButton)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel13)
                .addGap(26, 26, 26)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addGap(42, 42, 42)
                .addComponent(exitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(44, 44, 44))
        );

        jTabbedPane1.addTab("Exit", jPanel11);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        // TODO add your handling code here:
        String studentIn = (String) studentComboBox.getSelectedItem();
        String messageIn = messageInput.getText();

        try {
            AppManager.messageManager.addAdminMessage(studentIn, messageIn);
            JOptionPane.showMessageDialog(null, "Successfully sent!");
            messageInput.setText(" ");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminMainUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminMainUI.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_sendButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        messageInput.setText(" ");

    }//GEN-LAST:event_clearButtonActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        try {
            // TODO add your handling code here:
            String messageView = (String) (sentJlist.getSelectedValue());
            String messageIn;
            
            messageIn = AppManager.messageManager.getAdminMessage(messageView);
            sentTextArea.setText(messageIn);
            
        } catch (SQLException ex) {
            Logger.getLogger(AdminMainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        


    }//GEN-LAST:event_viewButtonActionPerformed

    private void viewReceivedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewReceivedButtonActionPerformed
        try {
            // TODO add your handling code here:
            String messageToView;
            messageToView = (String) (receivedJlist.getSelectedValue());
            
            
            String messageInfo = AppManager.messageManager.getStudentMessage(messageToView);
            receivedTextArea.setText(messageInfo);
        } catch (SQLException ex) {
            Logger.getLogger(AdminMainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_viewReceivedButtonActionPerformed

    private void refreshLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshLabelMouseClicked
        // TODO add your handling code here:
        DefaultListModel<String> listModelRefresh = new DefaultListModel<>();
        try {
            listModelRefresh.addAll(AppManager.messageManager.getAdminMessages());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, " SQL error");
            Logger.getLogger(AdminMainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        sentJlist.setModel(listModelRefresh);
    }//GEN-LAST:event_refreshLabelMouseClicked

    private void refreshRecLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshRecLabelMouseClicked
        // TODO add your handling code here:
        DefaultListModel<String> listModelRefreshRec = new DefaultListModel<>();
        try {
            listModelRefreshRec.addAll(AppManager.messageManager.getStudentMessages());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, " SQL error");
            Logger.getLogger(AdminMainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        receivedJlist.setModel(listModelRefreshRec);
    }//GEN-LAST:event_refreshRecLabelMouseClicked

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        DefaultListModel<String> listModelTopic = new DefaultListModel<>();
        String topic = (String) topicCombo.getSelectedItem();
        try {
            listModelTopic.addAll(AppManager.messageManager.getMessageFromTopic(topic));
        } catch (SQLException ex) {
            System.out.println("errorrrrrr");
            Logger.getLogger(AdminMainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        statsJlist.setModel(listModelTopic);
    }//GEN-LAST:event_searchButtonActionPerformed

    private void statsViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statsViewButtonActionPerformed
        // TODO add your handling code here:
        String messageToView = (String) (statsJlist.getSelectedValue());

        try {
            String messageInfo = AppManager.messageManager.getStudentMessage(messageToView);
            JOptionPane.showMessageDialog(null, messageInfo);
        } catch (SQLException ex) {
            Logger.getLogger(AdminMainUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_statsViewButtonActionPerformed

    private void searchStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchStudentButtonActionPerformed
        // TODO add your handling code here:
        String studentSelected = (String) studentsCombo.getSelectedItem();
        try {
            studentInfoTextArea.setText(AppManager.studentManager.getSpecificStudentInfo(studentSelected));
        } catch (SQLException ex) {
            Logger.getLogger(AdminMainUI.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_searchStudentButtonActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked

        JOptionPane.showMessageDialog(null, "Select a student from the drop down list\n" + " and click search to see their information!", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        //leave the app
        dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void labelllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelllMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Please do not use any form of quotation" + "\nmarks in any message/header inputs", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_labelllMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField academicText;
    private javax.swing.JTextArea adminTextArea;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JTextField facilitiesText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel labelll;
    private javax.swing.JTextArea messageInput;
    private javax.swing.JList<String> receivedJlist;
    private javax.swing.JTextArea receivedTextArea;
    private javax.swing.JTextField reddeliText;
    private javax.swing.JLabel refreshLabel;
    private javax.swing.JLabel refreshRecLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton searchStudentButton;
    private javax.swing.JButton sendButton;
    private javax.swing.JList<String> sentJlist;
    private javax.swing.JTextArea sentTextArea;
    private javax.swing.JList<String> statsJlist;
    private javax.swing.JButton statsViewButton;
    private javax.swing.JComboBox<String> studentComboBox;
    private javax.swing.JTextArea studentInfoTextArea;
    private javax.swing.JComboBox<String> studentsCombo;
    private javax.swing.JTextField studentsText;
    private javax.swing.JTextField teachersText;
    private javax.swing.JTextArea textArea;
    private javax.swing.JComboBox<String> topicCombo;
    private javax.swing.JTextField totalMessagesOutput;
    private javax.swing.JButton viewButton;
    private javax.swing.JButton viewReceivedButton;
    // End of variables declaration//GEN-END:variables
}
