/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Backend.AppManager;
import Backend.Message;
import Backend.MessageManager;
import Backend.StudentManager;
import Backend.DB;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
//

/**
 *
 * @author Narita
 */
public class StudentMainUI extends javax.swing.JFrame {

    
    private Message m;
    

    /**
     * Creates new form StudentMainUI
     */
    public StudentMainUI() {
        initComponents();
        setLocationRelativeTo(null);



        try {
            AppManager.init();//remember only have this on main screen
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StudentMainUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(StudentMainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //combo boxes topic
        String[] topics = {"Academics", "Facilities", "Teachers", "Red deli", "Students"};
        DefaultComboBoxModel<String> comboModel = new DefaultComboBoxModel<String>(topics);
        topicBox.setModel(comboModel);

        //subtopic
        String[] subAcademic = {"Time management", "Other"};
        DefaultComboBoxModel<String> comboModelA = new DefaultComboBoxModel<String>(subAcademic);
        subtopicCombobox.setModel(comboModelA);

        //Jlist
        DefaultListModel<String> listModel = new DefaultListModel<>();
        try {
            listModel.addAll(AppManager.messageManager.getSpecificStudentMessage(AppManager.studentManager.getCurrentStudent().getId())); //fix
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "SQL error");
            Logger.getLogger(StudentMainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        sentMessagesJList.setModel(listModel);
        DefaultListModel<String> listModel1 = new DefaultListModel<>();
        try {
            listModel1.addAll(AppManager.messageManager.getSpecificAdminMessage(AppManager.studentManager.getCurrentStudent().getId()));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "SQL error");
            Logger.getLogger(StudentMainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        receivedJlist.setModel(listModel1);

        //populate text fields with user's details
        
        
        nameTextfield.setText(AppManager.studentManager.getCurrentStudent().getName());
        surnameTextfield.setText(AppManager.studentManager.getCurrentStudent().getSurname());
        usernameTextfield.setText(AppManager.studentManager.getCurrentStudent().getUsername());
        passwordTextfield.setText(AppManager.studentManager.getCurrentStudent().getPassword());
        gradeTextfield.setText(AppManager.studentManager.getCurrentStudent().getGradeClass());
    }//end of main

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonTopicGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageInput = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        sendButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        topicBox = new javax.swing.JComboBox<>();
        titleInput = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        subtopicCombobox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        helpLabel = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sentMessagesJList = new javax.swing.JList<>();
        viewButton = new javax.swing.JButton();
        iconLabel2 = new javax.swing.JLabel();
        refreshSentScreenButton = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        sentTextArea = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        receivedJlist = new javax.swing.JList<>();
        viewReceivedButton = new javax.swing.JButton();
        iconLabel1 = new javax.swing.JLabel();
        refreshReceiveScreenButton = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        receivedTextArea = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nameTextfield = new javax.swing.JTextField();
        surnameTextfield = new javax.swing.JTextField();
        passwordTextfield = new javax.swing.JTextField();
        usernameTextfield = new javax.swing.JTextField();
        gradeTextfield = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        leaveButton = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(193, 173, 178));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(220, 220, 220));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(193, 173, 178));

        messageInput.setBackground(new java.awt.Color(255, 255, 255));
        messageInput.setColumns(20);
        messageInput.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        messageInput.setForeground(new java.awt.Color(0, 0, 0));
        messageInput.setRows(5);
        jScrollPane1.setViewportView(messageInput);

        jLabel1.setFont(new java.awt.Font("Constantia", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(68, 68, 68));
        jLabel1.setText("CONCERNS");

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(187, 187, 187));
        cancelButton.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(0, 0, 0));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        sendButton.setBackground(new java.awt.Color(187, 187, 187));
        sendButton.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        sendButton.setForeground(new java.awt.Color(0, 0, 0));
        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Topic:");

        topicBox.setBackground(new java.awt.Color(187, 187, 187));
        topicBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        topicBox.setForeground(new java.awt.Color(0, 0, 0));
        topicBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topicBoxActionPerformed(evt);
            }
        });

        titleInput.setBackground(new java.awt.Color(255, 255, 255));
        titleInput.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        titleInput.setForeground(new java.awt.Color(0, 0, 0));
        titleInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleInputActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Header:");

        subtopicCombobox.setBackground(new java.awt.Color(187, 187, 187));
        subtopicCombobox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        subtopicCombobox.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Sub-Topic:");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("On this page you can voice your concerns and express your own thoughts");

        helpLabel.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        helpLabel.setForeground(new java.awt.Color(0, 0, 0));
        helpLabel.setText("i");
        helpLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpLabelMouseClicked(evt);
            }
        });

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("on an array of topics with their subtopics by crafting your own messages to ");

        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("send to the Student Support Counil");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(titleInput, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(topicBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(subtopicCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel5)
                                            .addComponent(cancelButton)
                                            .addComponent(sendButton)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel19))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(helpLabel)
                                .addGap(16, 16, 16)))))
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(helpLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(topicBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(12, 12, 12)
                        .addComponent(subtopicCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelButton)
                        .addGap(22, 22, 22)
                        .addComponent(sendButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Concerns", jPanel2);

        jTabbedPane2.setBackground(new java.awt.Color(220, 220, 220));
        jTabbedPane2.setForeground(new java.awt.Color(0, 0, 0));
        jTabbedPane2.setOpaque(true);

        jPanel7.setBackground(new java.awt.Color(212, 186, 176));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });

        sentMessagesJList.setBackground(new java.awt.Color(255, 255, 255));
        sentMessagesJList.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(sentMessagesJList);

        viewButton.setBackground(new java.awt.Color(187, 187, 187));
        viewButton.setForeground(new java.awt.Color(0, 0, 0));
        viewButton.setText("VIEW");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        iconLabel2.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        iconLabel2.setForeground(new java.awt.Color(0, 0, 0));
        iconLabel2.setText("i");
        iconLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconLabel2MouseClicked(evt);
            }
        });

        refreshSentScreenButton.setForeground(new java.awt.Color(0, 0, 0));
        refreshSentScreenButton.setText("Refresh");
        refreshSentScreenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshSentScreenButtonMouseClicked(evt);
            }
        });

        sentTextArea.setBackground(new java.awt.Color(255, 255, 255));
        sentTextArea.setColumns(20);
        sentTextArea.setForeground(new java.awt.Color(0, 0, 0));
        sentTextArea.setRows(5);
        jScrollPane4.setViewportView(sentTextArea);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 334, Short.MAX_VALUE)
                        .addComponent(viewButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(refreshSentScreenButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iconLabel2)
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iconLabel2)
                    .addComponent(refreshSentScreenButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewButton)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Sent", jPanel5);

        jPanel6.setBackground(new java.awt.Color(212, 186, 176));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        receivedJlist.setBackground(new java.awt.Color(255, 255, 255));
        receivedJlist.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(receivedJlist);

        jPanel6.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 406, 149));

        viewReceivedButton.setBackground(new java.awt.Color(187, 187, 187));
        viewReceivedButton.setForeground(new java.awt.Color(0, 0, 0));
        viewReceivedButton.setText("VIEW");
        viewReceivedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewReceivedButtonActionPerformed(evt);
            }
        });
        jPanel6.add(viewReceivedButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, -1, -1));

        iconLabel1.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        iconLabel1.setForeground(new java.awt.Color(0, 0, 0));
        iconLabel1.setText("i");
        iconLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconLabel1MouseClicked(evt);
            }
        });
        jPanel6.add(iconLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 1, 10, 30));

        refreshReceiveScreenButton.setForeground(new java.awt.Color(0, 0, 0));
        refreshReceiveScreenButton.setText("Refresh");
        refreshReceiveScreenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshReceiveScreenButtonMouseClicked(evt);
            }
        });
        jPanel6.add(refreshReceiveScreenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        receivedTextArea.setBackground(new java.awt.Color(255, 255, 255));
        receivedTextArea.setColumns(20);
        receivedTextArea.setForeground(new java.awt.Color(0, 0, 0));
        receivedTextArea.setRows(5);
        jScrollPane5.setViewportView(receivedTextArea);

        jPanel6.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 406, 166));

        jTabbedPane2.addTab("Received", jPanel6);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane1.addTab("History", jPanel3);

        jPanel4.setBackground(new java.awt.Color(127, 134, 123));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Name:");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Surname:");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Username:");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Password:");

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Grade:");

        nameTextfield.setEditable(false);
        nameTextfield.setBackground(new java.awt.Color(255, 255, 255));
        nameTextfield.setForeground(new java.awt.Color(0, 0, 0));

        surnameTextfield.setEditable(false);
        surnameTextfield.setBackground(new java.awt.Color(255, 255, 255));
        surnameTextfield.setForeground(new java.awt.Color(0, 0, 0));

        passwordTextfield.setEditable(false);
        passwordTextfield.setBackground(new java.awt.Color(255, 255, 255));
        passwordTextfield.setForeground(new java.awt.Color(0, 0, 0));

        usernameTextfield.setEditable(false);
        usernameTextfield.setBackground(new java.awt.Color(255, 255, 255));
        usernameTextfield.setForeground(new java.awt.Color(0, 0, 0));

        gradeTextfield.setEditable(false);
        gradeTextfield.setBackground(new java.awt.Color(255, 255, 255));
        gradeTextfield.setForeground(new java.awt.Color(0, 0, 0));

        jLabel14.setFont(new java.awt.Font("Constantia", 3, 24)); // NOI18N
        jLabel14.setText("PROFILE");

        jLabel15.setText("View your student profile");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel17.setText("All information is confidential");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel14))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(passwordTextfield, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(usernameTextfield, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(surnameTextfield, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTextfield, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gradeTextfield)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel15))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel17)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(surnameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(passwordTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(gradeTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel10))
                .addGap(51, 51, 51)
                .addComponent(jLabel17)
                .addGap(42, 42, 42))
        );

        jTabbedPane1.addTab("Profile", jPanel4);

        jPanel8.setBackground(new java.awt.Color(239, 237, 231));

        leaveButton.setBackground(new java.awt.Color(200, 200, 196));
        leaveButton.setForeground(new java.awt.Color(0, 0, 0));
        leaveButton.setText("Exit");
        leaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveButtonActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Thank you for using the Student Support app");

        jLabel21.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Never be afraid to speak up or ask for help");

        jLabel22.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("You are not alone");

        jLabel23.setFont(new java.awt.Font("Ink Free", 2, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Take care");

        jLabel24.setFont(new java.awt.Font("Ink Free", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Bye for now!");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel21)))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addGap(162, 162, 162))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel23))
                            .addComponent(leaveButton))))
                .addGap(146, 146, 146))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel24)
                .addGap(38, 38, 38)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(leaveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Exit", jPanel8);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        try {
            // TODO add your handling code here:
            String messageToView;
            messageToView = (String) (sentMessagesJList.getSelectedValue());
            
            
            //
            String messageInfo = AppManager.messageManager.getStudentMessage(messageToView);
            sentTextArea.setText(messageInfo);
            
            // end of method
        } catch (SQLException ex) {
            Logger.getLogger(StudentMainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewButtonActionPerformed

    private void helpLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpLabelMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "How to work the app: \n" + "1.) Choose a heading and write it in the field labeled 'Header'. \n" + "2.) Write your message in the text area. \n" + "3.) Choose your topic and subtopic that relate to your message. \n" + "4.) Send!\n" + "\n Press Cancel to refresh", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
        // component - text - title
    }//GEN-LAST:event_helpLabelMouseClicked

    private void titleInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleInputActionPerformed

    private void topicBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topicBoxActionPerformed
        // TODO add your handling code here:
        if (topicBox.getSelectedItem().equals("Academics")) {
            String[] subAcademic = {"Time management", "Other"};
            DefaultComboBoxModel<String> comboModelA = new DefaultComboBoxModel<String>(subAcademic);
            subtopicCombobox.setModel(comboModelA);
        } else if (topicBox.getSelectedItem().equals("Facilities")) {
            String[] subFacilities = {"Bathrooms", " Classrooms", "Hallways", " Other"};
            DefaultComboBoxModel<String> comboModel0A = new DefaultComboBoxModel<String>(subFacilities);
            subtopicCombobox.setModel(comboModel0A);
        } else if (topicBox.getSelectedItem().equals("Teachers")) {
            String[] subTeachers = {"Mr B", "Mr Smee", " Mrs Bigara", " Mrs Jacobs"};
            DefaultComboBoxModel<String> comboModelAs = new DefaultComboBoxModel<String>(subTeachers);
            subtopicCombobox.setModel(comboModelAs);
        } else if (topicBox.getSelectedItem().equals("Red deli")) {
            String[] subReddeli = {"Service", "Food", "Costs", "Other"};
            DefaultComboBoxModel<String> comboModelAd = new DefaultComboBoxModel<String>(subReddeli);
            subtopicCombobox.setModel(comboModelAd);
        } else if (topicBox.getSelectedItem().equals("Students")) {
            String[] subStudents = {"Bullying", "Personal", "Other"};
            DefaultComboBoxModel<String> comboModelAk = new DefaultComboBoxModel<String>(subStudents);
            subtopicCombobox.setModel(comboModelAk);
        }
    }//GEN-LAST:event_topicBoxActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        // TODO add your handling code here:
        //String user = sm.getCurrentStudent(); //wrong logic
        String header = titleInput.getText();
        String message = messageInput.getText();
        String topic = (String) topicBox.getSelectedItem();
        String subtopic = (String) subtopicCombobox.getSelectedItem();

        
        m = new Message(topic, subtopic, header, message);

        try {
            AppManager.messageManager.addStudentMessage(m, AppManager.studentManager.getCurrentStudent().getId());
            messageInput.setText(" ");
            titleInput.setText(" ");
            JOptionPane.showMessageDialog(null, "Successfully sent!");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StudentMainUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(StudentMainUI.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("error");
        }
    }//GEN-LAST:event_sendButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        messageInput.setText(" ");
        titleInput.setText(" ");

    }//GEN-LAST:event_cancelButtonActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        // JOptionPane.showMessageDialog(null, "hellloooo"); //not gonna use this, maybe popup menu or sum?
    }//GEN-LAST:event_jLabel2MouseClicked

    private void viewReceivedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewReceivedButtonActionPerformed
        try {
            String getMessage = (String)receivedJlist.getSelectedValue();
            
            // TODO add your handling code here:
            
            String messageInfo = AppManager.messageManager.getAdminMessage(getMessage);
            receivedTextArea.setText(messageInfo);
        } catch (SQLException ex) {
            Logger.getLogger(StudentMainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_viewReceivedButtonActionPerformed

    private void refreshSentScreenButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshSentScreenButtonMouseClicked
        // TODO add your handling code here:
        DefaultListModel<String> listModel = new DefaultListModel<>();
        try {
            
            listModel.addAll(AppManager.messageManager.getSpecificStudentMessage(AppManager.studentManager.getCurrentStudent().getId())); //fix
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "SQL error");
            Logger.getLogger(StudentMainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        sentMessagesJList.setModel(listModel);

    }//GEN-LAST:event_refreshSentScreenButtonMouseClicked

    private void leaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_leaveButtonActionPerformed

    private void refreshReceiveScreenButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshReceiveScreenButtonMouseClicked
        // TODO add your handling code here:
        DefaultListModel<String> listModel1 = new DefaultListModel<>();
        try {
            listModel1.addAll(AppManager.messageManager.getSpecificAdminMessage(AppManager.studentManager.getCurrentStudent().getId()));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "SQL error");
            Logger.getLogger(StudentMainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        receivedJlist.setModel(listModel1);
    }//GEN-LAST:event_refreshReceiveScreenButtonMouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked

    }//GEN-LAST:event_jPanel7MouseClicked

    private void iconLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconLabel2MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Select one of the items and\n" + " click view to see its full contents.\n" + "Click refresh to refresh the screen", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_iconLabel2MouseClicked

    private void iconLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconLabel1MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Select one of the items and\n" + " click view to see its full contents.\n" + "Click refresh to refresh the screen", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_iconLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentMainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonTopicGroup;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField gradeTextfield;
    private javax.swing.JLabel helpLabel;
    private javax.swing.JLabel iconLabel1;
    private javax.swing.JLabel iconLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton leaveButton;
    private javax.swing.JTextArea messageInput;
    private javax.swing.JTextField nameTextfield;
    private javax.swing.JTextField passwordTextfield;
    private javax.swing.JList<String> receivedJlist;
    private javax.swing.JTextArea receivedTextArea;
    private javax.swing.JLabel refreshReceiveScreenButton;
    private javax.swing.JLabel refreshSentScreenButton;
    private javax.swing.JButton sendButton;
    private javax.swing.JList<String> sentMessagesJList;
    private javax.swing.JTextArea sentTextArea;
    private javax.swing.JComboBox<String> subtopicCombobox;
    private javax.swing.JTextField surnameTextfield;
    private javax.swing.JTextField titleInput;
    private javax.swing.JComboBox<String> topicBox;
    private javax.swing.JTextField usernameTextfield;
    private javax.swing.JButton viewButton;
    private javax.swing.JButton viewReceivedButton;
    // End of variables declaration//GEN-END:variables
}
